### PR TITLE
Implemented edge_rolling in python with tests

### PR DESCRIPTION
**Pull request by joseortiz3**
Implemented the most direct python translation of the vectorized R code and an appropriate test for ensuring equivalency between `edge` and `rolling_edge` in python.

Addresses https://github.com/eguidotti/bidask/issues/12 https://github.com/eguidotti/bidask/issues/9 https://github.com/eguidotti/bidask/issues/8

### CODE REVIEW

**Comment by joseortiz3** [comment]
Please see the test case when window_size = 2, or window_size = 1. All window_sizes >= 3 pass the test, but fail at window_size <= 2 due to mismatch of NaNs from `edge` with very small values (<`1e-8`) from `rolling_edge`.

I spent quite a lot of time trying track down why, but I still am not sure. At first I thought it had to do with the escape condition in `edge` to return `np.nan` if `pt`, `po`, or `pc` were 0, but replicating this same condition in `rolling_edge` didn't change anything.

For instance, when window_size=2 (below, `roll` is `rolling_edge` and `expected` is `edge`, offending rows shown), roll and expected have different NaN values at:
|      | roll         | expected | Open     | High     | Low      | Close    | last_open | last_high | last_low | last_close |
|------|--------------|----------|----------|----------|----------|----------|-----------|-----------|----------|------------|
| 113  | 4.656613e-10 | NaN      | 1.458753 | 1.458753 | 1.458753 | 1.458753 | 1.427500  | 1.458753  | 1.427500 | 1.458753   |
| 207  | 7.173121e-10 | NaN      | 2.564101 | 2.564101 | 2.564101 | 2.564101 | 2.599707  | 2.614939  | 2.564101 | 2.564101   |
| 364  | 1.324629e-09 | NaN      | 2.832997 | 2.832997 | 2.832997 | 2.832997 | 2.776515  | 2.832997  | 2.776515 | 2.832997   |
| 401  | 6.955005e-10 | NaN      | 2.258607 | 2.258607 | 2.258607 | 2.258607 | 2.193964  | 2.258607  | 2.193964 | 2.258607   |
| 429  | 0.000000e+00 | NaN      | 1.824052 | 1.824052 | 1.824052 | 1.824052 | 1.879073  | 1.879073  | 1.824052 | 1.824052   |
| ...  | ...          | ...      | ...      | ...      | ...      | ...      | ...       | ...       | ...      | ...        |
| 9601 | 9.301499e-10 | NaN      | 3.683719 | 3.683719 | 3.683719 | 3.683719 | 3.783243  | 3.783243  | 3.683719 | 3.683719   |
| 9819 | 1.339928e-09 | NaN      | 4.446167 | 4.446167 | 4.446167 | 4.446167 | 4.500941  | 4.500941  | 4.446167 | 4.446167   |
| 9862 | 1.798883e-09 | NaN      | 5.139985 | 5.139985 | 5.139985 | 5.139985 | 4.902133  | 5.139985  | 4.902133 | 5.139985   |
| 9899 | 1.004330e-09 | NaN      | 5.165314 | 5.165314 | 5.165314 | 5.165314 | 5.023252  | 5.165314  | 4.988500 | 5.165314   |
| 9941 | 3.500126e-10 | NaN      | 5.884242 | 5.884242 | 5.884242 | 5.884242 | 5.851965  | 5.884242  | 5.753185 | 5.884242   |

**Comment by eguidotti** [comment]
Yes, thank you for pointing this out. The estimator needs at least 3 observations to compute the spread. So using a window size < 3 makes no sense and the output should always be NaN. This can be forced, I guess, by setting `min_periods=3`. I'll need to fix it as well in the R implementation

**Comment by joseortiz3** [comment]
Ah, perfect. min_periods >= 3 because of terms like Var[x_{1,t}] where x_{1,t} depends on current and last prices, right? (hence, all Var terms would be zero if there are only two periods).

I enforced the restrictions in my latest commit.

**Comment by eguidotti** [comment]
Exactly. 

Maybe it is better to use `min_periods=3` by default and not accepting `None` or anything < 3. The reason is that the `window` parameter is not necessarily an integer in pandas. Therefore, using a time delta as the window parameter with min periods equal to None would still produce incorrect zero estimates when the time period does not include at least 3 observations. 

What do you think?

**Comment by joseortiz3** [comment]
Ohh yes.
[pandas rolling doc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html)
> min_periods : int, default None
> Minimum number of observations in window required to have a value; otherwise, result is np.nan.
> 
> For a window that is specified by an offset, min_periods will default to 1.
> 
> For a window that is specified by an integer, min_periods will default to the size of the window.

I propose that, if window is not an integer:
- if min_periods is None, we set it to 3.
- else if min_periods < 3, we raise ValueError

if window is integer:
- if min_periods is None, we check if window is > 3 because default in pandas is to set min_periods equal to window
- else if min_periods < 3, we raise ValueError

**Comment by eguidotti** [comment]
Maybe I'm missing something, but can't we simply set `min_periods=3` instead of `min_periods=None` as the default and check that `min_periods` is not `None`?

**Comment by joseortiz3** [comment]
I'm trying to match the default behavior of pandas rolling, which is default min_periods = None, if window is integer, min_periods := window (100% coverage), if window is not an integer, min_periods := smallest possible value (1 in general case, 3 here)

**Comment by joseortiz3** [comment]
I suppose min_periods=3 is a good default here, even if it isn't panda's default. I mean, who is going to do a rolling bid ask estimate and wants it to produce a series of 10 or 100 NaNs if one observation is missing from a window of 10, 100, etc?

**Comment by eguidotti** [comment]
Ah, I see! The difference is the handling of missing values. You are right, maybe it's better to match the default behavior by pandas.

An alternative option is to compute the number of non-missing observations in each period and set the estimate to missing for periods with less than 3 observations. This could be done using a rolling sum over a column of booleans indicating whether the open, high, low, and close prices are valid

**Comment by joseortiz3** [comment]
Hmm. We could do an invalid_mask (replace final estimate's masked rows with NaN). Something like this?

```
#
N_obs = (~(o.isna() | h.isna() | l.isna() | c.isna())).rolling(window).sum()
invalid_mask = N_obs < 3
```

Is this the correct condition, though? For instance, it doesn't appear that the estimate requires the latest close price, or the earliest open price, for example.

**Comment by eguidotti** [comment]
It should be:
```r
N_obs = (~(o.isna() | h.isna() | l.isna() | h1.isna() | l1.isna() | c1.isna())).rolling(window, **rolling_kwargs).sum()
invalid_mask = N_obs < 3  # or < 2? if pandas exludes the first observation in the window, it should be 2
```

**Comment by joseortiz3** [comment]
Hey, so I've been looking into this more lately but haven't had time to finish a new commit. Here are some notes:

- While the estimator needs three periods of data, the min_periods in the rolling_edge function should be `2` because the function uses the `.shift(1)` method to access the data at t-2 by shifting one from the t-1 row.
- The previously-mentioned issues where there are discrepancies between `rolling_edge` returning very small estimates <1e-8 whereas `edge` returns NaN for the same period appears to be resolved if I add the following to both functions:

```
    # Add to both edge.py and rolling_edge.py
    # eps is the smallest representable number such that 1.0 + eps != 1.0
    eps = np.finfo(v1.dtype).eps
    # Set variances to zero if they are numerically close or negative
    v1 = v1 * (v1 >= eps)
    v2 = v2 * (v2 >= eps)

    s2 = (v2*e1 + v1*e2) / (v1 + v2)
```

The problem appears to be that, sometimes, v1 or v2 ends up very close to zero, but not identically zero (equally often negative). I don't fully understand why, something to do with numerical stability. This occurs more often for the vectorized computation, perhaps because of how it is flattened. Again, I don't totally understand it.  But adding the above code to both functions causes the functions to match especially regarding NaN matching. So, I am considering adding the above block of code to both functions.

Alternatively or additionally, I am also considering relaxing the testing requirements so that, for example, if one estimator says S=1e-9 and the other says S=NaN, we forgive the discrepancy. I am kind of giving up trying to track down a better explanation of why the NaN placement is different.  I know that it isn't because of this line in `edge.py`:

```python
    # edge.py
    if pt == 0 or po == 0 or pc == 0:
        return np.nan
 ```
 
 Because all those rows are already NaN in `rolling_edge.py`. Similarly, that block of code you suggest:
 
 ```
 N_obs = (~(o.isna() | h.isna() | l.isna() | h1.isna() | l1.isna() | c1.isna())).rolling(window, **rolling_kwargs).sum()
invalid_mask = N_obs < 3  # or < 2? if pandas exludes the first observation in the window, it should be 2
```

May be redundant because pandas or numpy will generate a NaN value if it cannot access required data and this NaN will be propogated throughout the computation according to the IEEE standards for this computation that numpy implements; (in tests, it doesn't add any more NaNs)

**Comment by eguidotti** [comment]
Thanks a lot for your help; I'll dig deeper into it in the next days

**Comment by eguidotti** [comment]
Confirmed: the issue is due to numerical instability. Thanks a lot for pointing this out! It should be fixed now and the code should be ready for release. 

I've changed the function name to `edge_rolling`, and the rolling estimates: 
```py
rolling_estimates = edge_rolling(df=df, window=window, step=step, sign=sign)
```
are equivalent to:
```py
expected_estimates = []
for t in range(0, len(df), step):
    t1 = t + 1
    t0 = t1 - window
    expected_estimates.append(edge(
        df.Open.values[t0:t1],
        df.High.values[t0:t1],
        df.Low.values[t0:t1],
        df.Close.values[t0:t1],
        sign=sign
    ) if t0 >= 0 else np.nan)
```
for any window size 1, 2, 3, 4, etc. 

Note: I've added a couple of additional checks in `edge`. These are not essential and the code runs smoothly also without them. The reason I've added them is to avoid raising warnings with operations involving divisions by zero or other weird operations. This may also be helpful to simplify implementations in other languages that may treat these cases differently from numpy.

**Comment by joseortiz3** [comment]
I think this is really fantastic. Great work. The only change I made was adding documentation that `min_periods` and `window` are decremented by 1 to account for using .shift(1), as this is unexpected behavior to users familiar with pandas' `rolling` (but makes total sense here).

**Comment by joseortiz3** [comment]
Also, pandas rolling does not allow `float` for `window` and `min_periods`, so the check
```python
        if k in kwargs and isinstance(kwargs[k], (int, float)):
```
Can be simplified to
```python
        if k in kwargs and isinstance(kwargs[k], int):
```
Pandas rolling does however allow np integer types, so maybe the most thorough check is:
```python
        if k in kwargs and isinstance(kwargs[k], (int, np.integer)):
```
(and I saw pandas does this check internally when dealing with these user arguments)

I'll add this in case you agree

**Comment by eguidotti** [comment]
Great! I've added also `edge_expanding` to compute expanding estimates. The call
```py
expanding_estimates = edge_expanding(df=df, min_periods=min_periods, sign=sign)
```
is equivalent to
```py
expected_estimates = []
for t in range(0, len(df)):
    t1 = t + 1
    expected_estimates.append(edge(
        df.Open.values[0:t1],
        df.High.values[0:t1],
        df.Low.values[0:t1],
        df.Close.values[0:t1],
        sign=sign
    ) if t1 >= min_periods else np.nan)
```

I've moved the note that `min_periods` and `window` are decremented by 1 into the code (comments) because I believe it may be confusing for the average user. Overall, I'm wondering whether it is better to keep `**kwargs` for the rolling and expanding function or to select only the arguments we want to expose. For instance, the `axis` and `method` in the pandas functions are completely irrelevant here. On the other hand, pandas documentation is great and leaving `**kwargs` seems more flexible.

**Comment by eguidotti** [comment]
Updated the README with the new functionalities. Please feel free to improve it if you find that anything is unclear. After that, we should be ready for release

**Comment by joseortiz3** [comment]
I exposed the required parameter `window` because pandas rolling will error without it. No need to do this for expanding.

I added backwards-compatible (Python 3.7+) typehints for the `window` parameter that don't affect runtime imports (only imported during typehinting; this is similar to how pandas does typehinting except they didn't care to continue supporting python 3.7 typehinting)

If the type-hinting seems like too much (e.g. isn't minimalist enough), it can be replaced with 

```python
from typing import Union, Any

def ...
    window: Union[int, Any],
) -> pd.Series:
    """
    `window`: int, any type supported by pandas rolling
    """
```

I also modified the readme so that it has a sentence explaining that `min_periods` and `window`, when integer, are the number of periods used in each rolling estimate (rather than try to explain that it is because we used .shift(1)). A bit easier than trying to work through the equivalence example mentally.

**Comment by eguidotti** [comment]
Sounds great, thanks! I'd go for the minimalist option. 

I've now tried to estimate the bid-ask spread from second prices for bitcoin (BTCUSDT on Binance) and I get an estimate of `1.819844e-05` (~ 0.002% which seems correct) with the variances `v1` and `v2` estimated at `3.252480e-15` and `2.803589e-16` which are very close to the threshold `np.finfo(v1.dtype).eps`! I'm afraid that using this threshold is not a good option because it may create problems when estimating tiny spreads from high-frequency data. I'm still struggling with this...

**Comment by joseortiz3** [comment]
A difficult problem, for sure. I think the numerical stability issue that can be easily addressed in `edge` is that variance is being calculated by E[X²] - (E[X])² which suffers from potential [catastrophic cancellation](https://en.wikipedia.org/wiki/Catastrophic_cancellation). Maybe possible to replace with a [numerically-stable variance calculation](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance)? As for `edge_rolling` and `edge_expanding`, I'm not sure what can be done due to added complication of requiring flattening the computation for a single pass of rolling or expanding. 

edit: Or maybe some kind of pre-conditioning where the prices in log space are normalized and their differences are widened, and then the appropriate correction is applied to the final estimate after computation.

edit 2: also sorry I'm not being more helpful on this at the moment, I'm on vacation until the 26th.

**Comment by eguidotti** [comment]
So this should be fixed now! 🎉 Here are my comments for the last commit.

### Numerical (in)stability
The issue is solved by distinguishing between the cases where 1) the variance is zero because there are not enough valid observations and 2) the variance is zero because it is actually estimated at zero. The first case is identified with the condition that the sum of `tau` is `< 2` and we return `np.nan` in this case. The second case is identified with the condition that `v1+v2<=0` and we use `v1=v2=0.5` in this case (i.e., the simple average). This solves the mismatch between `0` and `np.nan` in the different versions and guarantees that `np.nan` means "invalid sample" and `0` means "zero estimate".

### Documentation
Still need to understand what is the best way to document the `kwargs`. In the meantime, I've added several comments in the code. I believe the new version of `edge` should become the new pseudocode and all other implementations should be updated accordingly.

### Tests
All tests pass successfully. I also run a quick speed test and the vectorized implementation is 100x faster than the original implementation on the sample data.

### Other tweaks
Further reduced the computational times by about 10% by avoiding repeated calculations.

**Pull request merged**
